// AUTO-GENERATED by scripts/build-illustration-assets.mjs — do not edit by hand.
// Run `npm run assets:illustrations` to regenerate.
export interface IllustrationMeta { ar: number; widths: number[]; fallbackWidth: number; }
export const ILLUSTRATIONS = {
  "becoming-ca": {
    "ar": 1,
    "widths": [
      160,
      240,
      320
    ],
    "fallbackWidth": 320
  },
  "time-to-renew": {
    "ar": 1,
    "widths": [
      160,
      240,
      320
    ],
    "fallbackWidth": 320
  },
  "run-a-clinic": {
    "ar": 1,
    "widths": [
      160,
      240,
      320
    ],
    "fallbackWidth": 320
  },
  "hands-on-training": {
    "ar": 1.491,
    "widths": [
      240,
      360,
      480
    ],
    "fallbackWidth": 480
  },
  "vitals": {
    "ar": 1,
    "widths": [
      240,
      360,
      480
    ],
    "fallbackWidth": 480
  },
  "certificate-moment": {
    "ar": 1,
    "widths": [
      220,
      330,
      440
    ],
    "fallbackWidth": 440
  },
  "evening-study": {
    "ar": 1.491,
    "widths": [
      280,
      360,
      520,
      680
    ],
    "fallbackWidth": 680
  },
  "empty-state": {
    "ar": 1,
    "widths": [
      160,
      240,
      320,
      400
    ],
    "fallbackWidth": 400
  },
  "clinic-dashboard": {
    "ar": 2.022,
    "widths": [
      380,
      560,
      760,
      1120,
      1456
    ],
    "fallbackWidth": 720
  },
  "oregon-path": {
    "ar": 2.022,
    "widths": [
      360,
      540,
      720,
      1080,
      1440
    ],
    "fallbackWidth": 720
  },
  "error-404": {
    "ar": 2.022,
    "widths": [
      280,
      420,
      560,
      840
    ],
    "fallbackWidth": 720
  }
} as const satisfies Record<string, IllustrationMeta>;
export type IllustrationName = keyof typeof ILLUSTRATIONS;
